// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ClipboardController from "./clipboard_controller"
import UrlFormController from "./account/url_form_controller"
import LanguageController from "./language_controller"

application.register("clipboard", ClipboardController)
application.register("url-form", UrlFormController)
application.register("language", LanguageController)
